### ISSUE TITLE
Proxy does start listening and then stopps?

### ISSUE THREAD

**Issue by jonaz** [brancz/kube-rbac-proxy#26]
I was debating where to put this issue (prometheus-operator or here)
Using kubernetes 1.11.5

I expect the kube-rbac-proxy-main pod to listen to 8443 and the kube-rbac-proxy-self to listen to 9443
It starts listening.. But after a while it just stopps and prints no error 
```
$ kubectl exec -ti --namespace=monitoring kube-state-metrics-7f8cbb777-4jk9b sh

~ $ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8082          0.0.0.0:*               LISTEN      -
tcp        0      0 10.42.4.17:42178        10.43.0.1:443           ESTABLISHED -
tcp        0      0 10.42.4.17:42174        10.43.0.1:443           ESTABLISHED -
tcp        2      0 :::8443                 :::*                    LISTEN      1/kube-rbac-proxy
tcp        2      0 :::9443                 :::*                    LISTEN      -
tcp      142      0 ::ffff:10.42.4.17:8443  ::ffff:10.42.6.14:57838 ESTABLISHED -
tcp      142      0 ::ffff:10.42.4.17:9443  ::ffff:10.42.6.14:50506 ESTABLISHED -
tcp      142      0 ::ffff:10.42.4.17:9443  ::ffff:10.42.6.14:50594 ESTABLISHED -
tcp      142      0 ::ffff:10.42.4.17:8443  ::ffff:10.42.6.14:57748 ESTABLISHED -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path
~ $ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8081          0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:8082          0.0.0.0:*               LISTEN      -
tcp        0      0 10.42.4.17:42856        10.43.0.1:443           ESTABLISHED -
tcp        0      0 10.42.4.17:42174        10.43.0.1:443           ESTABLISHED -
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node PID/Program name    Path

```

We use pretty standard jsonnet from kube-prometheus with no modifications to kube-state-metrics.
Generated kube-state-metrics-deployment looks like this: 
```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      containers:
      - args:
        - --secure-listen-address=:8443
        - --tls-cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8081/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy-main
        ports:
        - containerPort: 8443
          name: https-main
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --secure-listen-address=:9443
        - --tls-cipher-suites=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --upstream=http://127.0.0.1:8082/
        image: quay.io/coreos/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy-self
        ports:
        - containerPort: 9443
          name: https-self
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
      - args:
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        image: quay.io/coreos/kube-state-metrics:v1.5.0
        name: kube-state-metrics
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 150Mi
      - command:
        - /pod_nanny
        - --container=kube-state-metrics
        - --cpu=100m
        - --extra-cpu=2m
        - --memory=150Mi
        - --extra-memory=30Mi
        - --threshold=5
        - --deployment=kube-state-metrics
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/coreos/addon-resizer:1.0
        name: addon-resizer
        resources:
          limits:
            cpu: 50m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-state-metrics
```

i tried to add `--logtostderr`
and then i see this during startup
```
kube-state-metrics-597fc98779-wx84d kube-rbac-proxy-self I0118 14:53:27.868174       1 main.go:209] Generating self signed cert as no cert is provided
kube-state-metrics-597fc98779-wx84d kube-rbac-proxy-main I0118 14:53:27.467248       1 main.go:209] Generating self signed cert as no cert is provided
kube-state-metrics-597fc98779-wx84d kube-rbac-proxy-main I0118 14:53:42.469645       1 main.go:242] Listening securely on :8443
kube-state-metrics-597fc98779-wx84d kube-rbac-proxy-self I0118 14:53:36.268832       1 main.go:242] Listening securely on :9443
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.271446       1 main.go:80] Using default collectors
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.271542       1 main.go:88] Using all namespace
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.271554       1 main.go:124] metric white-blacklisting: blacklisting the following items: 
kube-state-metrics-597fc98779-wx84d kube-state-metrics W0118 14:53:28.271571       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.272776       1 main.go:166] Testing communication with server
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.284837       1 main.go:171] Running with Kubernetes cluster version: v1.11. git version: v1.11.5. git tree state: clean. commit: 753b2dbc622f5cc417845f0ff8a77f539a4213ea. platform: linux/amd64
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.284860       1 main.go:173] Communication with server successful
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.285139       1 main.go:182] Starting kube-state-metrics self metrics server: 127.0.0.1:8082
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.371624       1 builder.go:112] Active collectors: configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets
kube-state-metrics-597fc98779-wx84d kube-state-metrics I0118 14:53:28.371649       1 main.go:208] Starting metrics server: 127.0.0.1:8081
```
