### ISSUE TITLE
[HELP] Trying to expose Hubble UI with kube-rbac-proxy

### ISSUE THREAD

**Issue by dalvarezquiroga** [brancz/kube-rbac-proxy#286]
Hi, first thanks for the support and maintain this repo. 🥇 

We are trying to deploy this solution in a kubernetes cluster, basically to use [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) in front of [hubble ui.](https://docs.cilium.io/en/stable/gettingstarted/hubble/) to secure the paths.

Right now Hubble ui doesn't accept multi-tenant or at least the open source version. For that reason we want to use this tools as proxy and check if a given user/SA has access to a particular resource in a namespace. 

kubernetes version that we tried: **1.24 & 1.29** :

We are getting some examples from this page --> https://github.com/brancz/kube-rbac-proxy/tree/master/examples

You can find our configuration here:
deployment.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rbac-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-rbac-proxy
subjects:
- kind: ServiceAccount
  name: kube-rbac-proxy
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-rbac-proxy
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-rbac-proxy
  name: kube-rbac-proxy
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app: kube-rbac-proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-rbac-proxy
data:
  config-file.yaml: |+
    authorization:
      rewrites:
        byQueryParameter:
          name: "namespace"
      resourceAttributes:
        apiVersion: v1
        resource: namespace
        subresource: metrics
        namespace: "{{ .Value }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      securityContext:
        runAsUser: 65532
      serviceAccountName: kube-rbac-proxy
      containers:
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.16.0
        args:
        - "--insecure-listen-address=0.0.0.0:8443"
        - "--upstream=http://hubble-ui.kube-system.svc.cluster.local/"
        - "--config-file=/etc/kube-rbac-proxy/config-file.yaml"
        - "--logtostderr=true"
        - "--ignore-paths=/*.js,/*.css,/*.png,/icons/misc/*.svg,/api/ui.UI/GetEvents,/api/ui.UI/GetControlStream"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: config
          mountPath: /etc/kube-rbac-proxy
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: config
        configMap:
          name: kube-rbac-proxy

```

client-rbac.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-metrics
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-metrics
rules:
- apiGroups: [""]
  resources:
  - namespace/metrics
  verbs: ["get"]
```

**Result:**
![image](https://github.com/brancz/kube-rbac-proxy/assets/20278092/cd85f796-17ed-45cf-ad2f-bedada0b2fa0)
For test purposes we execute in our local a port-forward to the kube-rbac-proxy port and then use ModHeader to introduce the Bearer token.

Logs from kube-rbac-proxy:
`I0321 12:51:46.520456       1 log.go:245] http: proxy error: context canceled`

**The questions:**
Do you see something wrong from for the configuration? Or the proxy is not ready for managing GRPC connections?
We are lost.

Thanks! 👍

**Comment by ibihim** [comment]
## Does gRPC work with kube-rbac-proxy?

I would assume so. gRPC is just a binary payload of a http/2 connection (correct me if I am wrong). And http/2 should work.
kube-rbac-proxy doesn't inspect the payload. It reads the headers / path.

Hm, I remember that the examples were not very helpful for me to understand kube-rbac-proxy. Maybe it would make sense to make new ones, but as I am the only active maintainer, this is very low on the priority list.

If you want to see a more appropriate "example" for http/2, look here: https://github.com/brancz/kube-rbac-proxy/tree/master/test/e2e/http2. Obviously the `deployment-no-http2.yaml` verifies that it can be disabled (because of the protocol CVE), but the `deployment.yaml` is set up for http/2.
If you want to see the h2c variation, look here: https://github.com/brancz/kube-rbac-proxy/tree/master/test/e2e/h2c-upstream. In this use case, kube-rbac-proxy is used to create a TLS connection to the client and then kube-rbac-proxy talks locally non-TLS to the upstream service. kube-rbac-proxy is often being used to protect H2C services like Helm's Tiller in the older versions.

## Debugging

### HTTP, not HTTPS

Setup:

- You specified kube-rbac-proxy to listen on HTTP: `- "--insecure-listen-address=0.0.0.0:8443"`
- Your service listens on HTTP as well: `- "--upstream=http://hubble-ui.kube-system.svc.cluster.local/"`
- Your service is not on the same Pod.

If you are using HTTP without TLS and not mTLS, it is not a good idea to not have the cilium service running on a different pod. Otherwise, why should someone connect through the proxy?
If you are using HTTP/2 without TLS, did you specify some "insecure" flag on the upstream service? Usually you would run HTTP/2 over TLS. TLS can be easily used to negotiate other protocols (besides HTTP, like HTTP/2 or WebSocket). I never looked into h2c too much (h2c - HTTP/2 without TLS), but we support it.
If you want to use HTTP/2 without TLS, you might need to specify the `--upstream-force-h2c=true` flag as this is not the "normal" way to handle HTTP/2.

### kube-rbac-proxy as a side-car

Usually, you would load kube-rbac-proxy as a side-car (especially without mTLS). This means that you have a pod with two containers:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      serviceAccountName: kube-rbac-proxy
      containers:
        - name: kube-rbac-proxy
          image: quay.io/brancz/kube-rbac-proxy:local
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8081/"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
        - name: prometheus-example-app
          image: quay.io/brancz/prometheus-example-app:v0.1.0
          args:
            - "--bind=127.0.0.1:8081"
```

The cilium's server should listen to localhost:$PORT and kube-rbac-proxy is in front of it (the only one being able to connect to localhost:$PORT) that listens through a service and delegates to localhost:$PORT if authenticated and authorized.

### URL Rewrite

You specified that you want to make the authorization request rewritable with the query parameter `?namespace=value`.
This is a prometheus-use-case:

1. kube-rbac-proxy doesn't drop the query parameter, therefore upstream (cilium) needs to be able to interpret this param as well.
2. If I have a token from a SA that has GET on /metrics in another namespace, I could go with `?namespace=another-namespace`, through the proxy and it is up to the upstream server to deal with it. If the UI shows me a 404, but I can still click on the website around, I by-passed it. This works well with prometheus, which only responds with data for that namespace in the query parameter.

### WebSite

The website you loaded is from the same upstream? So the html website was loaded properly?

### Logs

Is this the only log entry (`I0321 12:51:46.520456       1 log.go:245] http: proxy error: context canceled`)? I don't want any business logic, just curious if there are some other warnings or interesting log entries wrt the configuration.

You should at least see complains about deprecated flag `--logtostderr` and `--insecure-listen-address`.

### Suggestion

The best option is to use the paid version, if you can afford it.
The second best option is to not run kube-rbac-proxy on the deprecated `--insecure-listen-address`.
Otherwise I would consider trying something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      securityContext:
        runAsUser: 65532
      serviceAccountName: kube-rbac-proxy
      containers:
      - name: hubble
        image: hubble/something
        args:
        - "--insecure-grpc"
        - "--listen-to=8080" 
      - name: kube-rbac-proxy
        image: quay.io/brancz/kube-rbac-proxy:v0.16.0
        args:
        - "--upstream-force-h2c=true"
        - "--insecure-listen-address=0.0.0.0:8443"
        - "--upstream=http://localhost:8080"
        - "--config-file=/etc/kube-rbac-proxy/config-file.yaml"
        - "--ignore-paths=/*.js,/*.css,/*.png,/icons/misc/*.svg,/api/ui.UI/GetEvents,/api/ui.UI/GetControlStream"
        - "--v=10"
        ports:
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: config
          mountPath: /etc/kube-rbac-proxy
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: config
        configMap:
          name: kube-rbac-proxy
```
