### ISSUE TITLE
exiting because of error: log: cannot create log: open /tmp/kube-rbac-proxy/xxx: permission denied

### ISSUE THREAD

**Issue by huanggze** [brancz/kube-rbac-proxy#54]
I had the following errors with v0.4.1 on one of my worker node (Other nodes have no problem). It causes node-exporter to crash. No idea what's the root cause

```
18770 main.go:213] Generating self signed cert as no cert is provided

2019-11-21T07:35:31.199545675Z log: exiting because of error: log: cannot create log: open /tmp/kube-rbac-proxy.centos01.unknownuser.log.INFO.20191121-073531.18770: permission denied
```

My deployment yaml is like
```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  # ...
spec:
  # ...
  template:
    # ...
    spec:
      volumes:
      # ...
      containers:
        - name: node-exporter
          # ...
        - name: kube-rbac-proxy
          image: 'quay.io/coreos/kube-rbac-proxy'
          args:
            - '--secure-listen-address=$(IP):9100'
            - '--upstream=http://127.0.0.1:9100/'
          ports:
            - name: https
              hostPort: 9100
              containerPort: 9100
              protocol: TCP
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccountName: node-exporter
      serviceAccount: node-exporter
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
      imagePullSecrets:
        - name: qingcloud
      schedulerName: default-scheduler
      # ...
```
